apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- statefulset-mysql.yaml
#- try-namespace.yaml # namespaces are not allowed to be created by apps team in project workloads
patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: catalog
      namespace: catalog