apiVersion: v1
kind: ConfigMap
metadata:
  name: carts-ack
  namespace: carts
data:
  CARTS_DYNAMODB_TABLENAME: "spoke-staging-carts-ack"
  CARTS_DYNAMODB_ENDPOINT: https://dynamodb.us-east-2.amazonaws.com