apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: items
  namespace: carts
  labels:
    app.kubernetes.io/created-by: eks-workshop  
spec:
  keySchema:
    - attributeName: id
      keyType: HASH
  attributeDefinitions:
    - attributeName: id
      attributeType: "S"
    - attributeName: customerId
      attributeType: "S"
  billingMode: PAY_PER_REQUEST
  tableName: "spoke-staging-carts-ack"
  globalSecondaryIndexes:
    - indexName: idx_global_customerId
      keySchema:
        - attributeName: customerId
          keyType: HASH
        - attributeName: id
          keyType: RANGE
      projection:
        projectionType: "ALL"